[book]
authors = ["mjiee"]
language = "en"
multilingual = false
src = "src"
title = "frontend notes"
description="前端学习笔记"

[output.html]
no-section-label = true
git-repository-url = "https://gitee.com/mjiee/frontendnotes.git"
git-repository-icon = "fa-github"
edit-url-template = "https://gitee.com/mjiee/frontendnotes/edit/master/{path}"
site-url = "/frontend/"
cname="book.mjiee.top"
input-404 = "assets/404.md"
